name: Daily Scrape and Upload

on:
  schedule:
    - cron: '0 2 * * *'  # প্রতি দিন ভোর ৮টায় (বাংলাদেশ সময়)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py

      - name: Upload to Google Drive
        run: |
          curl https://rclone.org/install.sh | bash
          rclone copy *.json gdrive:scraper-output -v
        env:
          RCLONE_CONFIG_GDRIVE_TYPE: drive
          RCLONE_CONFIG_GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
